--- 
apiVersion: v1
kind: Pod
metadata: 
  name: barbican
spec: 
  containers: 
    - 
      image: patrocinio/barbican
      name: barbican
      ports: 
        - 
          containerPort: 9311
  restartPolicy: Always

