apiVersion: v1
kind: Service
metadata:
  name: barbican-svc
spec:
  ports:
  - port: 9311  
    targetPort: 9311
    protocol: TCP
  externalIPs:
  - 23.246.208.98
  - 23.246.208.115 
  selector:
    app: barbican
