--- 
apiVersion: v1
kind: ReplicationController
metadata: 
  name: barbican
spec: 
  replicas: 2
  selector:
    app: barbican
  template:
    metadata:
      name: barbican
      labels:
        app: barbican
    spec:
      containers:
      - name: barbican
        image: patrocinio/barbican
        ports:
        - containerPort: 9311

